# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 18, 38, 28, 726000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 18, 38, 28, 724000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 18, 38, 28, 715000)),
        ),
    ]
