# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0003_auto_20190902_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployprojectapply',
            name='build_id',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 19, 9, 51, 26000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 19, 9, 51, 24000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 2, 19, 9, 51, 17000)),
        ),
    ]
