# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-03 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0004_auto_20190902_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployprojectapply',
            name='tester_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 8, 48, 18, 460000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 8, 48, 18, 458000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 8, 48, 18, 450000)),
        ),
    ]
