# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-06 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0006_auto_20190906_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployprojectapply',
            name='deploy_result',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='deployprojectapply',
            name='result',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 11, 21, 1, 26000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 11, 21, 1, 24000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 11, 21, 1, 16000)),
        ),
    ]
