# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-28 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0008_auto_20191025_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprestart',
            name='hash_id',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='apprestart',
            name='op_type',
            field=models.CharField(default=b'restart', max_length=10),
        ),
        migrations.AlterField(
            model_name='apprestart',
            name='group_task_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 14, 12, 24, 653000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 14, 12, 24, 651000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 14, 12, 24, 641000)),
        ),
    ]
