# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-28 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0009_auto_20191028_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprestart',
            name='task_id',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 15, 54, 47, 11000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 15, 54, 47, 9000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 15, 54, 47, 2000)),
        ),
    ]
