# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-28 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0010_auto_20191028_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprestart',
            name='hash_id',
        ),
        migrations.AlterField(
            model_name='apprestart',
            name='group_task_id',
            field=models.TextField(default=b'', max_length=4000),
        ),
        migrations.AlterField(
            model_name='apprestart',
            name='task_id',
            field=models.TextField(default=b'', max_length=2000),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 17, 15, 2, 172000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 17, 15, 2, 170000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 17, 15, 2, 163000)),
        ),
    ]
