# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-13 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0012_auto_20200115_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlSlowLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
                ('remote_host', models.CharField(blank=True, max_length=50)),
                ('query_time', models.DateTimeField()),
                ('sql_exc_time', models.FloatField()),
                ('sql_lock_time', models.FloatField()),
                ('sql_rows_examined', models.IntegerField(max_length=10)),
                ('sql_text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 10, 53, 25, 15000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 10, 53, 25, 13000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 10, 53, 25, 7000)),
        ),
    ]
