# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-19 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0014_auto_20200318_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostpowerapply',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 9, 11, 31, 456000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 9, 11, 31, 452000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 9, 11, 31, 441000)),
        ),
    ]
