# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-19 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0015_auto_20200319_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 10, 44, 21, 13000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='is_agree',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 10, 44, 21, 10000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 10, 44, 20, 999000)),
        ),
    ]
