# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-19 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0017_auto_20200319_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostpowerapply',
            name='apply_result',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 11, 18, 47, 169000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 11, 18, 47, 182000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 11, 18, 47, 167000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 11, 18, 47, 159000)),
        ),
    ]
