# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-31 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0018_auto_20200319_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='redis',
            name='conf',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 17, 8, 47, 423000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 17, 8, 47, 443000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 17, 8, 47, 420000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 17, 8, 47, 410000)),
        ),
    ]
