# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-31 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0019_auto_20200331_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redis',
            name='conf',
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 17, 19, 6, 35000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 17, 19, 6, 59000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 17, 19, 6, 30000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 17, 19, 6, 17000)),
        ),
    ]
