# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-31 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0021_auto_20200331_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='redisexeclog',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devopsApp.Redis'),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 18, 14, 8, 485000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 18, 14, 8, 503000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 18, 14, 8, 481000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 18, 14, 8, 470000)),
        ),
    ]
