# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-18 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0024_auto_20200513_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MysqlInfo',
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 14, 13, 36, 423000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 14, 13, 36, 431000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 14, 13, 36, 421000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 14, 13, 36, 414000)),
        ),
    ]
