# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-18 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0025_auto_20200518_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbClusterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('db_type', models.CharField(max_length=10)),
                ('service_name', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DbNodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=50)),
                ('conf_path', models.CharField(max_length=150)),
                ('base_path', models.CharField(max_length=150)),
                ('service_port', models.IntegerField(max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('cluster_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devopsApp.DbClusterInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 14, 28, 9, 545000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 14, 28, 9, 560000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 14, 28, 9, 543000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 14, 28, 9, 533000)),
        ),
    ]
