# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-22 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0026_auto_20200518_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbSqlApplyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('cluster_name', models.CharField(max_length=50)),
                ('schema_name', models.CharField(max_length=50)),
                ('apply_time', models.DateTimeField(default=datetime.datetime(2020, 5, 22, 9, 6, 17, 519000))),
                ('group_leader', models.CharField(max_length=50)),
                ('group_leader_agree', models.CharField(blank=True, max_length=50)),
                ('dba_agree', models.CharField(blank=True, max_length=50)),
                ('dba_not_agree_reson', models.CharField(max_length=1000)),
                ('is_dba_exec', models.CharField(blank=True, max_length=10)),
                ('sql', models.TextField()),
                ('is_success', models.CharField(max_length=10)),
                ('start_exec_time', models.DateTimeField(blank=True, null=True)),
                ('end_exec_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 9, 6, 17, 507000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 9, 6, 17, 516000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 9, 6, 17, 505000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 9, 6, 17, 498000)),
        ),
    ]
