# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-25 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0027_auto_20200522_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsqlapplyresult',
            name='apply_reson',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dbsqlapplyresult',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 16, 34, 18, 273000)),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 16, 34, 18, 258000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 16, 34, 18, 269000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 16, 34, 18, 254000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 16, 34, 18, 244000)),
        ),
    ]
