# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-18 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devopsApp', '0028_auto_20200525_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=128)),
                ('online_date', models.DateTimeField(default=datetime.datetime(2021, 6, 18, 10, 53, 25, 205000))),
                ('offline_date', models.DateTimeField(blank=True, null=True)),
                ('package_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('dockerfile_path', models.CharField(max_length=100)),
                ('latest_image', models.CharField(max_length=100)),
                ('deploy_yaml', models.CharField(max_length=100)),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devopsApp.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='dbsqlapplyresult',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 10, 53, 25, 204000)),
        ),
        migrations.AlterField(
            model_name='deployversion',
            name='deploy_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 10, 53, 25, 191000)),
        ),
        migrations.AlterField(
            model_name='hostpowerapply',
            name='apply_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 10, 53, 25, 201000)),
        ),
        migrations.AlterField(
            model_name='jenkinsdeploylog',
            name='deploy_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 10, 53, 25, 188000)),
        ),
        migrations.AlterField(
            model_name='service',
            name='online_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 10, 53, 25, 181000)),
        ),
    ]
